# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


# http://www.gotealeaf.com/blog/managing-environment-configuration-variables-in-rails

development:
  secret_key_base: 1074d19ef048d02d3002b3c7f6f90e851b6655b75aba973a3029a9ee3c0a0cd1158c91867a0f3e37ab76b7e010ecf9ae6914a34a95ea3e8ab0b5da90aa7eed04

test:
  secret_key_base: 187927e9b79aa3d4c3df62988fd5a671766d5ec8c0cb96a11d48b34f1f75e7b55a54fe1633f5c00041ef6e2ecffe0a873d181ddd8a4519e50d726a7969171e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  secret_key_base: 1074d19ef048d02d3002b3c7f6f90e851b6655b75aba973a3029a9ee3c0a0cd1158c91867a0f3e37ab76b7e010ecf9ae6914a34a95ea3e8ab0b5da90aa7eed04
